# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Posts(BaseModel):
    """
    An AI-generated article or post created by the Spartera Post Generator
    """ # noqa: E501
    date_created: Optional[datetime] = Field(default=None, description="Optional.")
    last_updated: Optional[datetime] = Field(default=None, description="Optional.")
    post_id: Optional[StrictStr] = Field(default=None, description="Unique identifier.")
    user_id: StrictStr = Field(description="User who created this post")
    company_id: StrictStr = Field(description="Company this post belongs to")
    title: StrictStr = Field(description="Article title")
    category: Optional[StrictStr] = Field(default=None, description="Article category (e.g., 'Sports', 'Business')")
    teaser: Optional[StrictStr] = Field(default=None, description="Article teaser/subtitle")
    content_html: StrictStr = Field(description="Generated article HTML content")
    insights_used: Optional[Dict[str, Any]] = Field(default=None, description="Array of insights used: [{asset_id, asset_name, value, runtime, success}]")
    generation_creativity: Optional[StrictInt] = Field(default=None, description="Creativity level (0-100), maps to AI temperature")
    generation_target_word_count: Optional[StrictInt] = Field(default=None, description="Target word count (null = auto)")
    generation_tone: Optional[StrictStr] = Field(default=None, description="Writing tone: professional, casual, technical, conversational")
    generation_include_citations: Optional[StrictBool] = Field(default=None, description="Whether to include data source citations")
    generation_subheading_count: Optional[StrictInt] = Field(default=None, description="Number of subheadings (2-5)")
    generation_temperature: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Actual temperature used for generation (0.0-2.0)")
    data_cost_credits: StrictInt = Field(description="Cost in credits for data insights")
    service_cost_credits: StrictInt = Field(description="Cost in credits for AI generation service")
    total_cost_credits: StrictInt = Field(description="Total cost in credits (data + service)")
    successful_insights_count: StrictInt = Field(description="Number of insights that succeeded")
    failed_insights_count: StrictInt = Field(description="Number of insights that failed")
    generation_time_ms: Optional[StrictInt] = Field(default=None, description="Time taken to generate article in milliseconds")
    is_published: StrictBool = Field(description="Whether this post has been published")
    published_at: Optional[datetime] = Field(default=None, description="When this post was published")
    view_count: StrictInt = Field(description="Number of times this post has been viewed")
    last_edited_at: Optional[datetime] = Field(default=None, description="When this post was last edited")
    __properties: ClassVar[List[str]] = ["date_created", "last_updated", "post_id", "user_id", "company_id", "title", "category", "teaser", "content_html", "insights_used", "generation_creativity", "generation_target_word_count", "generation_tone", "generation_include_citations", "generation_subheading_count", "generation_temperature", "data_cost_credits", "service_cost_credits", "total_cost_credits", "successful_insights_count", "failed_insights_count", "generation_time_ms", "is_published", "published_at", "view_count", "last_edited_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Posts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Posts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_created": obj.get("date_created"),
            "last_updated": obj.get("last_updated"),
            "post_id": obj.get("post_id"),
            "user_id": obj.get("user_id"),
            "company_id": obj.get("company_id"),
            "title": obj.get("title"),
            "category": obj.get("category"),
            "teaser": obj.get("teaser"),
            "content_html": obj.get("content_html"),
            "insights_used": obj.get("insights_used"),
            "generation_creativity": obj.get("generation_creativity"),
            "generation_target_word_count": obj.get("generation_target_word_count"),
            "generation_tone": obj.get("generation_tone"),
            "generation_include_citations": obj.get("generation_include_citations"),
            "generation_subheading_count": obj.get("generation_subheading_count"),
            "generation_temperature": obj.get("generation_temperature"),
            "data_cost_credits": obj.get("data_cost_credits"),
            "service_cost_credits": obj.get("service_cost_credits"),
            "total_cost_credits": obj.get("total_cost_credits"),
            "successful_insights_count": obj.get("successful_insights_count"),
            "failed_insights_count": obj.get("failed_insights_count"),
            "generation_time_ms": obj.get("generation_time_ms"),
            "is_published": obj.get("is_published"),
            "published_at": obj.get("published_at"),
            "view_count": obj.get("view_count"),
            "last_edited_at": obj.get("last_edited_at")
        })
        return _obj


