# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.favorites_api import FavoritesApi


class TestFavoritesApi(unittest.TestCase):
    """FavoritesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FavoritesApi()

    def tearDown(self) -> None:
        pass

    def test_create_favorites(self) -> None:
        """Test case for create_favorites

        POST /companies/{company_id}/users/{user_id}/favorites
        """
        pass

    def test_delete_favorites(self) -> None:
        """Test case for delete_favorites

        Delete single favorite by ID (unfavorite an asset)
        """
        pass

    def test_get_favorites_by_id(self) -> None:
        """Test case for get_favorites_by_id

        Get a list of all favorites for a specific user
        """
        pass

    def test_get_favorites_by_id_users(self) -> None:
        """Test case for get_favorites_by_id_users

        Get single favorite by ID
        """
        pass

    def test_get_favorites_by_id_users_category(self) -> None:
        """Test case for get_favorites_by_id_users_category

        Get all favorites for the specified user in a specific category
        """
        pass

    def test_get_favorites_by_id_users_check(self) -> None:
        """Test case for get_favorites_by_id_users_check

        Check if the specified user has favorited a specific asset
        """
        pass

    def test_get_favorites_by_id_users_uncategorized(self) -> None:
        """Test case for get_favorites_by_id_users_uncategorized

        Get all favorites for the specified user that don't have a category
        """
        pass

    def test_update_favorites(self) -> None:
        """Test case for update_favorites

        Update an existing favorite by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
