# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.alerts_api import AlertsApi


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlertsApi()

    def tearDown(self) -> None:
        pass

    def test_create_alerts(self) -> None:
        """Test case for create_alerts

        POST /companies/{company_id}/users/{user_id}/alerts
        """
        pass

    def test_delete_alerts(self) -> None:
        """Test case for delete_alerts

        Delete single alert by ID
        """
        pass

    def test_get_alerts_by_id(self) -> None:
        """Test case for get_alerts_by_id

        Get a list of all alerts for a specific user
        """
        pass

    def test_get_alerts_by_id_asset_all(self) -> None:
        """Test case for get_alerts_by_id_asset_all

        Get all alerts for a specific asset
        """
        pass

    def test_get_alerts_by_id_users(self) -> None:
        """Test case for get_alerts_by_id_users

        Get single alert by ID
        """
        pass

    def test_get_alerts_by_id_users_asset(self) -> None:
        """Test case for get_alerts_by_id_users_asset

        Get all alerts for a specific asset (by user)
        """
        pass

    def test_update_alerts(self) -> None:
        """Test case for update_alerts

        Update an existing alert by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
