# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.storage_engines_api import StorageEnginesApi


class TestStorageEnginesApi(unittest.TestCase):
    """StorageEnginesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageEnginesApi()

    def tearDown(self) -> None:
        pass

    def test_cloud_providers_provider_id_storage_engines_engine_id_get(self) -> None:
        """Test case for cloud_providers_provider_id_storage_engines_engine_id_get

        Get single storage engine by ID
        """
        pass

    def test_cloud_providers_provider_id_storage_engines_get(self) -> None:
        """Test case for cloud_providers_provider_id_storage_engines_get

        Get a list of all storage engines
        """
        pass


if __name__ == '__main__':
    unittest.main()
