# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.24.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.companies_company_id_users_user_id_alerts_asset_asset_id_get200_response import CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response

class TestCompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response(unittest.TestCase):
    """CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response:
        """Test CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response`
        """
        model = CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response()
        if include_optional:
            return CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response(
                message = 'success',
                data = spartera_api_sdk.models.alerts.Alerts(
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    alert_id = 56, 
                    asset_id = '', 
                    user_id = '', 
                    company_id = '', 
                    is_active = True, )
            )
        else:
            return CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response(
                message = 'success',
                data = spartera_api_sdk.models.alerts.Alerts(
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    alert_id = 56, 
                    asset_id = '', 
                    user_id = '', 
                    company_id = '', 
                    is_active = True, ),
        )
        """

    def testCompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response(self):
        """Test CompaniesCompanyIdUsersUserIdAlertsAssetAssetIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
