# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.update_asset_price_history200_response_data import UpdateAssetPriceHistory200ResponseData

class TestUpdateAssetPriceHistory200ResponseData(unittest.TestCase):
    """UpdateAssetPriceHistory200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAssetPriceHistory200ResponseData:
        """Test UpdateAssetPriceHistory200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAssetPriceHistory200ResponseData`
        """
        model = UpdateAssetPriceHistory200ResponseData()
        if include_optional:
            return UpdateAssetPriceHistory200ResponseData(
                aph_id = ''
            )
        else:
            return UpdateAssetPriceHistory200ResponseData(
                aph_id = '',
        )
        """

    def testUpdateAssetPriceHistory200ResponseData(self):
        """Test UpdateAssetPriceHistory200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
