# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.update_favorites200_response import UpdateFavorites200Response

class TestUpdateFavorites200Response(unittest.TestCase):
    """UpdateFavorites200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFavorites200Response:
        """Test UpdateFavorites200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateFavorites200Response`
        """
        model = UpdateFavorites200Response()
        if include_optional:
            return UpdateFavorites200Response(
                message = 'success',
                data = spartera_api_sdk.models.update_favorites_200_response_data.updateFavorites_200_response_data(
                    favorite_id = '', )
            )
        else:
            return UpdateFavorites200Response(
                message = 'success',
                data = spartera_api_sdk.models.update_favorites_200_response_data.updateFavorites_200_response_data(
                    favorite_id = '', ),
        )
        """

    def testUpdateFavorites200Response(self):
        """Test UpdateFavorites200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
