# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.get_alerts_by_id200_response import GetAlertsById200Response

class TestGetAlertsById200Response(unittest.TestCase):
    """GetAlertsById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAlertsById200Response:
        """Test GetAlertsById200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAlertsById200Response`
        """
        model = GetAlertsById200Response()
        if include_optional:
            return GetAlertsById200Response(
                message = 'success',
                data = spartera_api_sdk.models.alerts.Alerts(
                    date_created = '2025-04-01T00:00:00Z', 
                    last_updated = '2025-04-01T00:00:00Z', 
                    alert_id = 1, 
                    asset_id = 'asset_id_abc123', 
                    user_id = 'user_id_abc123', 
                    company_id = 'company_id_abc123', 
                    is_active = True, )
            )
        else:
            return GetAlertsById200Response(
                message = 'success',
                data = spartera_api_sdk.models.alerts.Alerts(
                    date_created = '2025-04-01T00:00:00Z', 
                    last_updated = '2025-04-01T00:00:00Z', 
                    alert_id = 1, 
                    asset_id = 'asset_id_abc123', 
                    user_id = 'user_id_abc123', 
                    company_id = 'company_id_abc123', 
                    is_active = True, ),
        )
        """

    def testGetAlertsById200Response(self):
        """Test GetAlertsById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
