# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.list_asset_usecases200_response import ListAssetUsecases200Response

class TestListAssetUsecases200Response(unittest.TestCase):
    """ListAssetUsecases200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAssetUsecases200Response:
        """Test ListAssetUsecases200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAssetUsecases200Response`
        """
        model = ListAssetUsecases200Response()
        if include_optional:
            return ListAssetUsecases200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.asset_usecases.AssetUsecases(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        auc_id = 1, 
                        auc_name = 'Example Name', 
                        slug = 'example-slug', 
                        auc_description = 'Example description.', )
                    ]
            )
        else:
            return ListAssetUsecases200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.asset_usecases.AssetUsecases(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        auc_id = 1, 
                        auc_name = 'Example Name', 
                        slug = 'example-slug', 
                        auc_description = 'Example description.', )
                    ],
        )
        """

    def testListAssetUsecases200Response(self):
        """Test ListAssetUsecases200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
