# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.create_endpoints200_response import CreateEndpoints200Response

class TestCreateEndpoints200Response(unittest.TestCase):
    """CreateEndpoints200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEndpoints200Response:
        """Test CreateEndpoints200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEndpoints200Response`
        """
        model = CreateEndpoints200Response()
        if include_optional:
            return CreateEndpoints200Response(
                message = 'success',
                data = spartera_api_sdk.models.create_endpoints_200_response_data.createEndpoints_200_response_data(
                    endpoint_id = '', )
            )
        else:
            return CreateEndpoints200Response(
                message = 'success',
                data = spartera_api_sdk.models.create_endpoints_200_response_data.createEndpoints_200_response_data(
                    endpoint_id = '', ),
        )
        """

    def testCreateEndpoints200Response(self):
        """Test CreateEndpoints200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
