# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.list_storage_engines200_response import ListStorageEngines200Response

class TestListStorageEngines200Response(unittest.TestCase):
    """ListStorageEngines200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListStorageEngines200Response:
        """Test ListStorageEngines200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListStorageEngines200Response`
        """
        model = ListStorageEngines200Response()
        if include_optional:
            return ListStorageEngines200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.storage_engines.StorageEngines(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        engine_id = 1, 
                        provider_id = 1, 
                        service_name = 'Example Name', 
                        engine_type = 'EDW', 
                        integration_complete = True, 
                        test_func_complete = True, )
                    ]
            )
        else:
            return ListStorageEngines200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.storage_engines.StorageEngines(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        engine_id = 1, 
                        provider_id = 1, 
                        service_name = 'Example Name', 
                        engine_type = 'EDW', 
                        integration_complete = True, 
                        test_func_complete = True, )
                    ],
        )
        """

    def testListStorageEngines200Response(self):
        """Test ListStorageEngines200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
