# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.update_asset_price_history200_response import UpdateAssetPriceHistory200Response

class TestUpdateAssetPriceHistory200Response(unittest.TestCase):
    """UpdateAssetPriceHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAssetPriceHistory200Response:
        """Test UpdateAssetPriceHistory200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAssetPriceHistory200Response`
        """
        model = UpdateAssetPriceHistory200Response()
        if include_optional:
            return UpdateAssetPriceHistory200Response(
                message = 'success',
                data = spartera_api_sdk.models.update_asset_price_history_200_response_data.updateAssetPriceHistory_200_response_data(
                    aph_id = '', )
            )
        else:
            return UpdateAssetPriceHistory200Response(
                message = 'success',
                data = spartera_api_sdk.models.update_asset_price_history_200_response_data.updateAssetPriceHistory_200_response_data(
                    aph_id = '', ),
        )
        """

    def testUpdateAssetPriceHistory200Response(self):
        """Test UpdateAssetPriceHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
