# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.list_cloud_providers200_response import ListCloudProviders200Response

class TestListCloudProviders200Response(unittest.TestCase):
    """ListCloudProviders200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCloudProviders200Response:
        """Test ListCloudProviders200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCloudProviders200Response`
        """
        model = ListCloudProviders200Response()
        if include_optional:
            return ListCloudProviders200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.cloud_providers.CloudProviders(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        provider_id = 1, 
                        name = 'Example Name', 
                        parent_company = 'example_value', 
                        marketing_homepage_url = 'https://example.com', )
                    ]
            )
        else:
            return ListCloudProviders200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.cloud_providers.CloudProviders(
                        date_created = '2025-04-01T00:00:00Z', 
                        last_updated = '2025-04-01T00:00:00Z', 
                        provider_id = 1, 
                        name = 'Example Name', 
                        parent_company = 'example_value', 
                        marketing_homepage_url = 'https://example.com', )
                    ],
        )
        """

    def testListCloudProviders200Response(self):
        """Test ListCloudProviders200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
