# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.cloudprovider import Cloudprovider

class TestCloudprovider(unittest.TestCase):
    """Cloudprovider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cloudprovider:
        """Test Cloudprovider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cloudprovider`
        """
        model = Cloudprovider()
        if include_optional:
            return Cloudprovider(
                provider_id = '',
                name = '',
                parent_company = '',
                marketing_homepage_url = '',
                date_created = '',
                last_updated = '',
                active = ''
            )
        else:
            return Cloudprovider(
                name = '',
        )
        """

    def testCloudprovider(self):
        """Test Cloudprovider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
