# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.get_asset_price_history_by_id200_response import GetAssetPriceHistoryById200Response

class TestGetAssetPriceHistoryById200Response(unittest.TestCase):
    """GetAssetPriceHistoryById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetPriceHistoryById200Response:
        """Test GetAssetPriceHistoryById200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetPriceHistoryById200Response`
        """
        model = GetAssetPriceHistoryById200Response()
        if include_optional:
            return GetAssetPriceHistoryById200Response(
                message = 'success',
                data = spartera_api_sdk.models.asset_price_history.AssetPriceHistory(
                    date_created = '2025-04-01T00:00:00Z', 
                    last_updated = '2025-04-01T00:00:00Z', 
                    aph_id = 'aph_id_abc123', 
                    asset_id = 'asset_id_abc123', 
                    endpoint_id = 'endpoint_id_abc123', 
                    price_usd = 5.0, 
                    date_ended = '2025-04-01T00:00:00Z', )
            )
        else:
            return GetAssetPriceHistoryById200Response(
                message = 'success',
                data = spartera_api_sdk.models.asset_price_history.AssetPriceHistory(
                    date_created = '2025-04-01T00:00:00Z', 
                    last_updated = '2025-04-01T00:00:00Z', 
                    aph_id = 'aph_id_abc123', 
                    asset_id = 'asset_id_abc123', 
                    endpoint_id = 'endpoint_id_abc123', 
                    price_usd = 5.0, 
                    date_ended = '2025-04-01T00:00:00Z', ),
        )
        """

    def testGetAssetPriceHistoryById200Response(self):
        """Test GetAssetPriceHistoryById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
