# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.24.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.companies_company_id_assets_asset_id_prices_aph_id_patch200_response_data import CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData

class TestCompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData(unittest.TestCase):
    """CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData:
        """Test CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData`
        """
        model = CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData()
        if include_optional:
            return CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData(
                aph_id = ''
            )
        else:
            return CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData(
                aph_id = '',
        )
        """

    def testCompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData(self):
        """Test CompaniesCompanyIdAssetsAssetIdPricesAphIdPatch200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
