# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.24.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.companies_company_id_connections_post200_response import CompaniesCompanyIdConnectionsPost200Response

class TestCompaniesCompanyIdConnectionsPost200Response(unittest.TestCase):
    """CompaniesCompanyIdConnectionsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesCompanyIdConnectionsPost200Response:
        """Test CompaniesCompanyIdConnectionsPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesCompanyIdConnectionsPost200Response`
        """
        model = CompaniesCompanyIdConnectionsPost200Response()
        if include_optional:
            return CompaniesCompanyIdConnectionsPost200Response(
                message = 'success',
                data = spartera_api_sdk.models._companies__company_id__connections_post_200_response_data._companies__company_id__connections_post_200_response_data(
                    connection_id = '', )
            )
        else:
            return CompaniesCompanyIdConnectionsPost200Response(
                message = 'success',
                data = spartera_api_sdk.models._companies__company_id__connections_post_200_response_data._companies__company_id__connections_post_200_response_data(
                    connection_id = '', ),
        )
        """

    def testCompaniesCompanyIdConnectionsPost200Response(self):
        """Test CompaniesCompanyIdConnectionsPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
