# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.24.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.companies_company_id_api_keys_api_key_id_get200_response import CompaniesCompanyIdApiKeysApiKeyIdGet200Response

class TestCompaniesCompanyIdApiKeysApiKeyIdGet200Response(unittest.TestCase):
    """CompaniesCompanyIdApiKeysApiKeyIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesCompanyIdApiKeysApiKeyIdGet200Response:
        """Test CompaniesCompanyIdApiKeysApiKeyIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesCompanyIdApiKeysApiKeyIdGet200Response`
        """
        model = CompaniesCompanyIdApiKeysApiKeyIdGet200Response()
        if include_optional:
            return CompaniesCompanyIdApiKeysApiKeyIdGet200Response(
                message = 'success',
                data = spartera_api_sdk.models.api_keys.ApiKeys(
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    api_key_id = 56, 
                    user_id = '', 
                    company_id = '', 
                    role_id = 56, 
                    name = '', 
                    expiration_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return CompaniesCompanyIdApiKeysApiKeyIdGet200Response(
                message = 'success',
                data = spartera_api_sdk.models.api_keys.ApiKeys(
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    api_key_id = 56, 
                    user_id = '', 
                    company_id = '', 
                    role_id = 56, 
                    name = '', 
                    expiration_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )
        """

    def testCompaniesCompanyIdApiKeysApiKeyIdGet200Response(self):
        """Test CompaniesCompanyIdApiKeysApiKeyIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
