# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.api_keys_input import ApiKeysInput

class TestApiKeysInput(unittest.TestCase):
    """ApiKeysInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeysInput:
        """Test ApiKeysInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeysInput`
        """
        model = ApiKeysInput()
        if include_optional:
            return ApiKeysInput(
                user_id = 'user_id_abc123',
                company_id = 'company_id_abc123',
                role_id = 1,
                key_type = 'key_abc123',
                is_system_generated = True,
                mcp_deployment_id = 'mcp_deployment_id_abc123',
                endpoint_id = 'endpoint_id_abc123',
                name = 'Example Name',
                expiration_date_utc = '2025-04-01T00:00:00Z'
            )
        else:
            return ApiKeysInput(
                company_id = 'company_id_abc123',
                role_id = 1,
        )
        """

    def testApiKeysInput(self):
        """Test ApiKeysInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
