# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.postgen_integrations_input import PostgenIntegrationsInput

class TestPostgenIntegrationsInput(unittest.TestCase):
    """PostgenIntegrationsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostgenIntegrationsInput:
        """Test PostgenIntegrationsInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostgenIntegrationsInput`
        """
        model = PostgenIntegrationsInput()
        if include_optional:
            return PostgenIntegrationsInput(
                company_id = 'company_id_abc123',
                user_id = 'user_id_abc123',
                platform = 'example_value',
                platform_name = 'Example Name',
                credentials_secret_name = 'Example Name',
                is_active = True,
                last_used_at = '2025-04-01T00:00:00Z'
            )
        else:
            return PostgenIntegrationsInput(
                company_id = 'company_id_abc123',
                user_id = 'user_id_abc123',
                platform = 'example_value',
                platform_name = 'Example Name',
                credentials_secret_name = 'Example Name',
        )
        """

    def testPostgenIntegrationsInput(self):
        """Test PostgenIntegrationsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
