# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompaniesApi()

    def tearDown(self) -> None:
        pass

    def test_companies_company_id_analytics_assets_get(self) -> None:
        """Test case for companies_company_id_analytics_assets_get

        Get asset performance analytics     Query params: start_date, end_date, limit, sort_by, include
        """
        pass

    def test_companies_company_id_analytics_customers_get(self) -> None:
        """Test case for companies_company_id_analytics_customers_get

        Get customer analytics including growth and segmentation     Query params: start_date, end_date, group_by, segment_by
        """
        pass

    def test_companies_company_id_analytics_dashboard_get(self) -> None:
        """Test case for companies_company_id_analytics_dashboard_get

        Get comprehensive dashboard analytics for seller dashboard     Includes all metrics needed for dashboard charts in one call     Query params: start_date, end_date, period (day/week/month/quarter)
        """
        pass

    def test_companies_company_id_analytics_sales_get(self) -> None:
        """Test case for companies_company_id_analytics_sales_get

        Get sales over time analytics     Query params: start_date, end_date, group_by (day/week/month/quarter), metrics
        """
        pass

    def test_companies_company_id_get(self) -> None:
        """Test case for companies_company_id_get

        Get details of the requestor's own company
        """
        pass

    def test_companies_company_id_objects_get(self) -> None:
        """Test case for companies_company_id_objects_get

        Get all objects (connections, assets) of a single company
        """
        pass

    def test_companies_company_id_patch(self) -> None:
        """Test case for companies_company_id_patch

        Update an existing company by ID
        """
        pass

    def test_companies_company_id_requests_plan_get(self) -> None:
        """Test case for companies_company_id_requests_plan_get

        Get the total number of requests allocated in the company's current subscription plan.
        """
        pass

    def test_companies_company_id_requests_usage_get(self) -> None:
        """Test case for companies_company_id_requests_usage_get

        Get company request usage data for a specific month. Returns JSON metrics by default or CSV logs when download parameter is included.
        """
        pass


if __name__ == '__main__':
    unittest.main()
