# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.asset_price_history_api import AssetPriceHistoryApi


class TestAssetPriceHistoryApi(unittest.TestCase):
    """AssetPriceHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetPriceHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_companies_company_id_assets_asset_id_prices_active_get(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_active_get

        Get the currently active price for an asset
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_aph_id_delete(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_aph_id_delete

        Delete single price history record by ID
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_aph_id_get(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_aph_id_get

        Get single price history record by ID
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_aph_id_patch(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_aph_id_patch

        Update an existing price history record by ID
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_calculate_credits_post(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_calculate_credits_post

        Calculate the credit equivalent for a given USD price without saving
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_discount_post(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_discount_post

        Apply a discount to the active price for an asset
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_get(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_get

        Get all price history records for a specific asset
        """
        pass

    def test_companies_company_id_assets_asset_id_prices_post(self) -> None:
        """Test case for companies_company_id_assets_asset_id_prices_post

        Create a new price history record for an asset
        """
        pass


if __name__ == '__main__':
    unittest.main()
