# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.companies_company_id_users_user_id_alerts_get200_response import CompaniesCompanyIdUsersUserIdAlertsGet200Response

class TestCompaniesCompanyIdUsersUserIdAlertsGet200Response(unittest.TestCase):
    """CompaniesCompanyIdUsersUserIdAlertsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompaniesCompanyIdUsersUserIdAlertsGet200Response:
        """Test CompaniesCompanyIdUsersUserIdAlertsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompaniesCompanyIdUsersUserIdAlertsGet200Response`
        """
        model = CompaniesCompanyIdUsersUserIdAlertsGet200Response()
        if include_optional:
            return CompaniesCompanyIdUsersUserIdAlertsGet200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.alert.Alert(
                        alert_id = '', 
                        asset_id = '', 
                        user_id = '', 
                        company_id = '', 
                        alert_type = '', 
                        is_active = '', 
                        last_triggered = '', 
                        date_created = '', 
                        last_updated = '', 
                        active = '', )
                    ]
            )
        else:
            return CompaniesCompanyIdUsersUserIdAlertsGet200Response(
                message = 'success',
                data = [
                    spartera_api_sdk.models.alert.Alert(
                        alert_id = '', 
                        asset_id = '', 
                        user_id = '', 
                        company_id = '', 
                        alert_type = '', 
                        is_active = '', 
                        last_triggered = '', 
                        date_created = '', 
                        last_updated = '', 
                        active = '', )
                    ],
        )
        """

    def testCompaniesCompanyIdUsersUserIdAlertsGet200Response(self):
        """Test CompaniesCompanyIdUsersUserIdAlertsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
