# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 1.25.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.models.update_connections200_response_data import UpdateConnections200ResponseData

class TestUpdateConnections200ResponseData(unittest.TestCase):
    """UpdateConnections200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateConnections200ResponseData:
        """Test UpdateConnections200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateConnections200ResponseData`
        """
        model = UpdateConnections200ResponseData()
        if include_optional:
            return UpdateConnections200ResponseData(
                connection_id = ''
            )
        else:
            return UpdateConnections200ResponseData(
                connection_id = '',
        )
        """

    def testUpdateConnections200ResponseData(self):
        """Test UpdateConnections200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
