# coding: utf-8

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spartera_api_sdk.api.favorites_api import FavoritesApi


class TestFavoritesApi(unittest.TestCase):
    """FavoritesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FavoritesApi()

    def tearDown(self) -> None:
        pass

    def test_companies_company_id_users_user_id_favorites_category_category_get(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_category_category_get

        Get all favorites for the specified user in a specific category
        """
        pass

    def test_companies_company_id_users_user_id_favorites_check_asset_id_get(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_check_asset_id_get

        Check if the specified user has favorited a specific asset
        """
        pass

    def test_companies_company_id_users_user_id_favorites_favorite_id_delete(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_favorite_id_delete

        Delete single favorite by ID (unfavorite an asset)
        """
        pass

    def test_companies_company_id_users_user_id_favorites_favorite_id_get(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_favorite_id_get

        Get single favorite by ID
        """
        pass

    def test_companies_company_id_users_user_id_favorites_favorite_id_patch(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_favorite_id_patch

        Update an existing favorite by ID
        """
        pass

    def test_companies_company_id_users_user_id_favorites_get(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_get

        Get a list of all favorites for a specific user
        """
        pass

    def test_companies_company_id_users_user_id_favorites_post(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_post

        POST /companies/{company_id}/users/{user_id}/favorites
        """
        pass

    def test_companies_company_id_users_user_id_favorites_uncategorized_get(self) -> None:
        """Test case for companies_company_id_users_user_id_favorites_uncategorized_get

        Get all favorites for the specified user that don't have a category
        """
        pass


if __name__ == '__main__':
    unittest.main()
