# coding: utf-8

# flake8: noqa

"""
    Spartera API Documentation

    Auto-generated API documentation for REST services of the Spartera platform

    The version of the OpenAPI document: 0.0.0
    Contact: support@spartera.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.10"

# import apis into sdk package
from spartera_api_sdk.api.api_keys_api import APIKeysApi
from spartera_api_sdk.api.alerts_api import AlertsApi
from spartera_api_sdk.api.asset_price_history_api import AssetPriceHistoryApi
from spartera_api_sdk.api.assets_api import AssetsApi
from spartera_api_sdk.api.companies_api import CompaniesApi
from spartera_api_sdk.api.connections_api import ConnectionsApi
from spartera_api_sdk.api.favorites_api import FavoritesApi
from spartera_api_sdk.api.users_api import UsersApi

# import ApiClient
from spartera_api_sdk.api_response import ApiResponse
from spartera_api_sdk.api_client import ApiClient
from spartera_api_sdk.configuration import Configuration
from spartera_api_sdk.exceptions import OpenApiException
from spartera_api_sdk.exceptions import ApiTypeError
from spartera_api_sdk.exceptions import ApiValueError
from spartera_api_sdk.exceptions import ApiKeyError
from spartera_api_sdk.exceptions import ApiAttributeError
from spartera_api_sdk.exceptions import ApiException

# import models into sdk package
from spartera_api_sdk.models.alert import Alert
from spartera_api_sdk.models.apikey import Apikey
from spartera_api_sdk.models.asset import Asset
from spartera_api_sdk.models.assetpricehistory import Assetpricehistory
from spartera_api_sdk.models.company import Company
from spartera_api_sdk.models.connection import Connection
from spartera_api_sdk.models.error import Error
from spartera_api_sdk.models.favorite import Favorite
from spartera_api_sdk.models.inline_object import InlineObject
from spartera_api_sdk.models.inline_object1 import InlineObject1
from spartera_api_sdk.models.inline_object2 import InlineObject2
from spartera_api_sdk.models.inline_object3 import InlineObject3
from spartera_api_sdk.models.user import User
